//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika3EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullView
    {
        public int ID_Purchase { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string PurchaseName { get; set; }
        public int PurchasePrice { get; set; }
        public int ID_Store { get; set; }
        public string StoreName { get; set; }
        public string StoreCityPlace { get; set; }
        public Nullable<int> Director_ID { get; set; }
        public string DirectorSurName { get; set; }
        public string DirectorName { get; set; }
        public string DirectorSecondName { get; set; }
        public string CustomerSurName { get; set; }
        public string CustomerName { get; set; }
        public string CustomerSecondName { get; set; }
    }
}
